development:
  bucket: rectangle_images_dev
  access_key_id: 	
  secret_access_key: 
test:
  bucket: rectangle_images_dev
  access_key_id: 	
  secret_access_key: 
production:
  bucket: rectangle_images_prod
  access_key_id: 	
  secret_access_key: 
